### ISSUE TITLE
auth not found for both CLI and library

### ISSUE THREAD

**Issue by sime** [pwmckenna/node-travis-ci#24]
I'm trying to use this library for the first time and really struggling to get past the authentication stage. Both CLI and the library is failing.

```bash
$ travis-ci auth github --github_token=123
auth not found
```

```javascript
const Travis = require("travis-ci");
const GITHUB_OAUTH_TOKEN = "123";

const travis = new Travis({
  pro: true,
  version: "2.0.0",
});

travis.authenticate({
  github_token: GITHUB_OAUTH_TOKEN,
}, (err) => {
  console.log("yippe");
});
```

```bash
$ node travis.js
/Users/simon.males/Development/villagepeopleapi/node_modules/travis-ci/lib/travis-ci.js:118
    this.auth.github.post(msg, function (err, res) {
             ^

TypeError: Cannot read property 'github' of undefined
    at TravisClient._authenticateGithubToken (/Users/simon.males/Development/villagepeopleapi/node_modules/travis-ci/lib/travis-ci.js:118:14)
    at TravisClient.authenticate (/Users/simon.males/Development/villagepeopleapi/node_modules/travis-ci/lib/travis-ci.js:181:21)
    at Object.<anonymous> (/Users/simon.males/Development/villagepeopleapi/travis.js:9:8)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
```

Specifically, `this.auth` is not defined anywhere in the application.

**Comment by ljharb** [comment]
Hmm, this is confusing. Absolutely you're right, it's not defined anywhere, but it's referenced *as if it does* in both tests and the implementation.

**Comment by sime** [comment]
Sorry, I was meant to delete this.

It was my own error :|
